# Generated by Django 3.2.2 on 2021-05-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='apostolic',
            field=models.CharField(default='what is the name of your pastor', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='christ',
            field=models.CharField(default='what is the name of your pastor', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='household',
            field=models.CharField(default='what is the name of your pastor', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='mountain',
            field=models.CharField(default='what is the name of your pastor', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='redemmed',
            field=models.CharField(default='what is the name of your pastor', max_length=200),
        ),
    ]
